name: Sample GitHub Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:

env:
  WORKFLOW_VAR: "workflow-var-value"

jobs:
  
  JobOne:
    name: "Job One"
    runs-on: ubuntu-latest

    outputs:
      JobOneVariableOutput: ${{ steps.JobOneStepTwo.outputs.JOB1_GH_OUTPUT_VAR }}

    env:
      JOBS1_VAR: "jobs1-var-value"

    steps:
      - name: "Job1 - Step1"
        run: |
          set -euo pipefail
          echo "JOBS1_VAR::$JOBS1_VAR"
          echo "JOB1_STEP1_VAR::$JOB1_STEP1_VAR"

        env:
          JOB1_STEP1_VAR: 'Hello from Job1 - Step1'
    
      - name: "Job1 - Step2"
        id: Job1Step2
        run: |
          echo "WORKFLOW_VAR::$WORKFLOW_VAR"
          echo "JOBS1_VAR::$JOBS1_VAR"
          echo "JOB1_STEP1_VAR::$JOB1_STEP1_VAR"
          echo "JOB2_STEP2_VAR::$JOB1_STEP2_VAR"
          echo "JOB1_GH_ENV_VAR=job2-gh-env-var-value" >> $GITHUB_ENV
          echo "JOB1_GH_OUTPUT_VAR=job2-gh-output-var-value" >> $GITHUB_OUTPUT

        env:
          JOB1_STEP2_VAR: 'Hello from Job1 - Step2'

  JobTwo:
    needs: [JobOne]
    name: "Job Two"
    runs-on: ubuntu-latest

    steps:
    - name: "Job2 - Step1"
      run: |
        echo "WORKFLOW_VAR::$WORKFLOW_VAR"
        echo "JOBS1_VAR::$JOBS1_VAR"
        echo "JOB1_STEP1_VAR::$JOB1_STEP1_VAR"
        echo "JOB1_STEP2_VAR::$JOB1_STEP2_VAR"
        echo "JOB1_GH_ENV_VAR::$JOB1_GH_ENV_VAR"        
        echo "JOB1_GH_OUTPUT_VAR::${{ needs.JobOne.outputs.JobOneVariableOutput }}"